// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	emails "github.com/gasser707/go-gql-server/utils/emails"
	mock "github.com/stretchr/testify/mock"
)

// EmailServiceInterface is an autogenerated mock type for the EmailServiceInterface type
type EmailServiceInterface struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: email
func (_m *EmailServiceInterface) SendEmail(email emails.EmailInterface) error {
	ret := _m.Called(email)

	var r0 error
	if rf, ok := ret.Get(0).(func(emails.EmailInterface) error); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
