// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EmailAdaptorInterface is an autogenerated mock type for the EmailAdaptorInterface type
type EmailAdaptorInterface struct {
	mock.Mock
}

// SendReceiptEmail provides a mock function with given fields: sender, to, sellerName, buyerName, imageID, imageTitle, paymentMethod
func (_m *EmailAdaptorInterface) SendReceiptEmail(sender string, to []string, sellerName string, buyerName string, imageID string, imageTitle string, paymentMethod string) {
	_m.Called(sender, to, sellerName, buyerName, imageID, imageTitle, paymentMethod)
}

// SendResetPassEmail provides a mock function with given fields: sender, to, name, resetLink
func (_m *EmailAdaptorInterface) SendResetPassEmail(sender string, to []string, name string, resetLink string) {
	_m.Called(sender, to, name, resetLink)
}

// SendWelcomeEmail provides a mock function with given fields: sender, to, name
func (_m *EmailAdaptorInterface) SendWelcomeEmail(sender string, to []string, name string) {
	_m.Called(sender, to, name)
}
