// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	emails "github.com/gasser707/go-gql-server/utils/emails"
	mock "github.com/stretchr/testify/mock"
)

// EmailServiceInterface is an autogenerated mock type for the EmailServiceInterface type
type EmailServiceInterface struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: ctx, email
func (_m *EmailServiceInterface) SendEmail(ctx context.Context, email emails.EmailInterface) error {
	ret := _m.Called(ctx, email)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, emails.EmailInterface) error); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
