// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	emails "github.com/gasser707/go-gql-server/utils/emails"
	mock "github.com/stretchr/testify/mock"
)

// EmailClientInterface is an autogenerated mock type for the EmailClientInterface type
type EmailClientInterface struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: email, emailContent
func (_m *EmailClientInterface) SendEmail(email emails.EmailInterface, emailContent string) error {
	ret := _m.Called(email, emailContent)

	var r0 error
	if rf, ok := ret.Get(0).(func(emails.EmailInterface, string) error); ok {
		r0 = rf(email, emailContent)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
