apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: shotify.com
      http:
        paths:
          - path: /query
            pathType: Prefix
            backend:
              service:
                name: shotify-srv
                port:
                  number: 8080
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: gql-ide-srv
                port:
                  number: 4000
