// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	graphql "github.com/99designs/gqlgen/graphql"
	mock "github.com/stretchr/testify/mock"
)

// StorageOperatorInterface is an autogenerated mock type for the StorageOperatorInterface type
type StorageOperatorInterface struct {
	mock.Mock
}

// DeleteImage provides a mock function with given fields: ctx, path
func (_m *StorageOperatorInterface) DeleteImage(ctx context.Context, path string) error {
	ret := _m.Called(ctx, path)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadImage provides a mock function with given fields: ctx, img, imgName, path
func (_m *StorageOperatorInterface) UploadImage(ctx context.Context, img *graphql.Upload, imgName string, path string) (string, error) {
	ret := _m.Called(ctx, img, imgName, path)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *graphql.Upload, string, string) string); ok {
		r0 = rf(ctx, img, imgName, path)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *graphql.Upload, string, string) error); ok {
		r1 = rf(ctx, img, imgName, path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
