// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	databases "github.com/gasser707/go-gql-server/databases/models"
	mock "github.com/stretchr/testify/mock"
)

// AuthRepoInterface is an autogenerated mock type for the AuthRepoInterface type
type AuthRepoInterface struct {
	mock.Mock
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *AuthRepoInterface) GetUserByEmail(ctx context.Context, email string) (*databases.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *databases.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *databases.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*databases.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
