// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	databases "github.com/gasser707/go-gql-server/databases/models"
	mock "github.com/stretchr/testify/mock"
)

// ImagesRepoInterface is an autogenerated mock type for the ImagesRepoInterface type
type ImagesRepoInterface struct {
	mock.Mock
}

// CountImageSales provides a mock function with given fields: ctx, imgId
func (_m *ImagesRepoInterface) CountImageSales(ctx context.Context, imgId int) (int, error) {
	ret := _m.Called(ctx, imgId)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, int) int); ok {
		r0 = rf(ctx, imgId)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, imgId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, dbImg
func (_m *ImagesRepoInterface) Create(ctx context.Context, dbImg *databases.Image) (int64, error) {
	ret := _m.Called(ctx, dbImg)

	var r0 int64
	if rf, ok := ret.Get(0).(func(context.Context, *databases.Image) int64); ok {
		r0 = rf(ctx, dbImg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *databases.Image) error); ok {
		r1 = rf(ctx, dbImg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, imgId, userId
func (_m *ImagesRepoInterface) Delete(ctx context.Context, imgId int, userId int) error {
	ret := _m.Called(ctx, imgId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) error); ok {
		r0 = rf(ctx, imgId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteImageLabels provides a mock function with given fields: ctx, imgId
func (_m *ImagesRepoInterface) DeleteImageLabels(ctx context.Context, imgId int) error {
	ret := _m.Called(ctx, imgId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, imgId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPublic provides a mock function with given fields: ctx
func (_m *ImagesRepoInterface) GetAllPublic(ctx context.Context) ([]*databases.Image, error) {
	ret := _m.Called(ctx)

	var r0 []*databases.Image
	if rf, ok := ret.Get(0).(func(context.Context) []*databases.Image); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*databases.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByFilter provides a mock function with given fields: ctx, filter
func (_m *ImagesRepoInterface) GetByFilter(ctx context.Context, filter string) ([]*databases.Image, error) {
	ret := _m.Called(ctx, filter)

	var r0 []*databases.Image
	if rf, ok := ret.Get(0).(func(context.Context, string) []*databases.Image); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*databases.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, imgId, userId
func (_m *ImagesRepoInterface) GetById(ctx context.Context, imgId int, userId int) (*databases.Image, []string, error) {
	ret := _m.Called(ctx, imgId, userId)

	var r0 *databases.Image
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *databases.Image); ok {
		r0 = rf(ctx, imgId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*databases.Image)
		}
	}

	var r1 []string
	if rf, ok := ret.Get(1).(func(context.Context, int, int) []string); ok {
		r1 = rf(ctx, imgId, userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, imgId, userId)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetImageIfOwner provides a mock function with given fields: ctx, imgId, userId
func (_m *ImagesRepoInterface) GetImageIfOwner(ctx context.Context, imgId int, userId int) (*databases.Image, error) {
	ret := _m.Called(ctx, imgId, userId)

	var r0 *databases.Image
	if rf, ok := ret.Get(0).(func(context.Context, int, int) *databases.Image); ok {
		r0 = rf(ctx, imgId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*databases.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, imgId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetImageLabels provides a mock function with given fields: ctx, imgId
func (_m *ImagesRepoInterface) GetImageLabels(ctx context.Context, imgId int) ([]string, error) {
	ret := _m.Called(ctx, imgId)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context, int) []string); ok {
		r0 = rf(ctx, imgId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, imgId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertImageLabels provides a mock function with given fields: ctx, imgId, labels
func (_m *ImagesRepoInterface) InsertImageLabels(ctx context.Context, imgId int, labels []*databases.Label) error {
	ret := _m.Called(ctx, imgId, labels)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, []*databases.Label) error); ok {
		r0 = rf(ctx, imgId, labels)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: ctx, id, img
func (_m *ImagesRepoInterface) Update(ctx context.Context, id int, img *databases.Image) error {
	ret := _m.Called(ctx, id, img)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int, *databases.Image) error); ok {
		r0 = rf(ctx, id, img)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
