// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	databases "github.com/gasser707/go-gql-server/databases/models"
	mock "github.com/stretchr/testify/mock"
)

// SalesRepoInterface is an autogenerated mock type for the SalesRepoInterface type
type SalesRepoInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: sale
func (_m *SalesRepoInterface) Create(sale *databases.Sale) (int64, error) {
	ret := _m.Called(sale)

	var r0 int64
	if rf, ok := ret.Get(0).(func(*databases.Sale) int64); ok {
		r0 = rf(sale)
	} else {
		r0 = ret.Get(0).(int64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*databases.Sale) error); ok {
		r1 = rf(sale)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: userId
func (_m *SalesRepoInterface) GetAll(userId int) ([]databases.Sale, error) {
	ret := _m.Called(userId)

	var r0 []databases.Sale
	if rf, ok := ret.Get(0).(func(int) []databases.Sale); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]databases.Sale)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetImageById provides a mock function with given fields: imgId, userId
func (_m *SalesRepoInterface) GetImageById(imgId int, userId int) (*databases.Image, error) {
	ret := _m.Called(imgId, userId)

	var r0 *databases.Image
	if rf, ok := ret.Get(0).(func(int, int) *databases.Image); ok {
		r0 = rf(imgId, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*databases.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = rf(imgId, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
