apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-persistent-storage
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volumeclaim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - image: mysql:latest
          name: mysql-db
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: pwd
              # valueFrom:
              #   secretKeyRef:
              #     name: mysql
              #     key: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/minesql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-volumeclaim

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-srv
spec:
  selector:
    app: mysql-db
  ports:
    - name: db
      port: 3306
      targetPort: 3306
      protocol: TCP
