// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	emails "github.com/gasser707/go-gql-server/utils/emails"
	mock "github.com/stretchr/testify/mock"
)

// EmailFactoryInterface is an autogenerated mock type for the EmailFactoryInterface type
type EmailFactoryInterface struct {
	mock.Mock
}

// GenerateEmailContent provides a mock function with given fields: email
func (_m *EmailFactoryInterface) GenerateEmailContent(email emails.EmailInterface) string {
	ret := _m.Called(email)

	var r0 string
	if rf, ok := ret.Get(0).(func(emails.EmailInterface) string); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
