// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package databases

var TableNames = struct {
	Images string
	Labels string
	Sales  string
	Users  string
}{
	Images: "images",
	Labels: "labels",
	Sales:  "sales",
	Users:  "users",
}
